<?php return array(
    'root' => array(
        'pretty_version' => 'dev-master',
        'version' => 'dev-master',
        'type' => 'library',
        'install_path' => __DIR__ . '/../',
        'aliases' => array(),
        'reference' => 'e2b1b29be1f0ee369051ea1f1c672defcaf03a42',
        'name' => '__root__',
        'dev' => true,
    ),
    'versions' => array(
        '__root__' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'type' => 'library',
            'install_path' => __DIR__ . '/../',
            'aliases' => array(),
            'reference' => 'e2b1b29be1f0ee369051ea1f1c672defcaf03a42',
            'dev_requirement' => false,
        ),
        'smalot/pdfparser' => array(
            'pretty_version' => 'v2.11.0',
            'version' => '2.11.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../smalot/pdfparser',
            'aliases' => array(),
            'reference' => 'ac8e6678b0940e4b2ccd5caadd3fb18e68093be6',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-mbstring' => array(
            'pretty_version' => 'v1.31.0',
            'version' => '1.31.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-mbstring',
            'aliases' => array(),
            'reference' => '85181ba99b2345b0ef10ce42ecac37612d9fd341',
            'dev_requirement' => false,
        ),
    ),
);
